### ISSUE TITLE
PermissionError: [Errno 13] Unable to create file (unable to open file: name = './checkpoints/yolov4-416', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302) 

### ISSUE THREAD

**Issue by byq-luo** [duongttr/vehicles-counting-yolov4-deepsort#2]
PermissionError: [Errno 13] Unable to create file (unable to open file: name = './checkpoints/yolov4-416', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)

**Comment by duongttr** [comment]
This question is not clear to me. Depending on the message of the error, I think you didn't give permission for Python script to create files on your computer. I have 2 options for you:

**1. Run python script in cmd with administrator** (Usually works)
- If you use MacOS, please put `sudo` keyword before every statement you run. E.g. `sudo python convert_model.py`
- If you use Windows, open cmd with `Run as Administrator` and change directory to the folder of the project, then run the python script normally.

**2. Move project folder to another place or disk** (Optional, I'm not sure it will work or not)

If the two options above don't work, please let me know clearly where you received this error.

**Comment by byq-luo** [comment]
> 
tf_op_layer_Reshape_10 (TensorF [(None, None, None)] 0           tf_op_layer_boolean_mask_1/Gather
                                                                 tf_op_layer_Reshape_10/shape[0][0
__________________________________________________________________________________________________
tf_op_layer_concat_16 (TensorFl [(None, None, None)] 0           tf_op_layer_concat_15[0][0]
                                                                 tf_op_layer_Reshape_10[0][0]
==================================================================================================
Total params: 64,041,685
Trainable params: 63,975,381
Non-trainable params: 66,304
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "save_model.py", line 62, in <module>
    app.run(main)
  File "C:\Users\Administrator.BNH-20210405RRL\anaconda3\envs\yolov4-gpu\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\Administrator.BNH-20210405RRL\anaconda3\envs\yolov4-gpu\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "save_model.py", line 58, in main
    save_tf()
  File "save_model.py", line 55, in save_tf
    model.save(FLAGS.output)
  File "C:\Users\Administrator.BNH-20210405RRL\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\engine\network.py", line 1171, in save
    signatures)
  File "C:\Users\Administrator.BNH-20210405RRL\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\saving\save.py", line 109, in save_model
    model, filepath, overwrite, include_optimizer)
  File "C:\Users\Administrator.BNH-20210405RRL\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 86, in save_model_to_hdf5
    f = h5py.File(filepath, mode='w')
  File "C:\Users\Administrator.BNH-20210405RRL\anaconda3\envs\yolov4-gpu\lib\site-packages\h5py\_hl\files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\Users\Administrator.BNH-20210405RRL\anaconda3\envs\yolov4-gpu\lib\site-packages\h5py\_hl\files.py", line 226, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 126, in h5py.h5f.create
PermissionError: [Errno 13] Unable to create file (unable to open file: name = './checkpoints/yolov4-416', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)

**Comment by duongttr** [comment]
Hi @byq-luo,
Have you tried two options above?
```bash
sudo python save_model.py --weights ./yolov4_final.weights --output ./checkpoints/yolov4-416 --model yolov4
```

**Comment by byq-luo** [comment]
> * Windows,

Windows 10
